# Generated by Django 2.0.3 on 2018-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Item',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fitemname', models.CharField(max_length=255)),
                ('fmusician', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation_Flow',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fuserid', models.CharField(max_length=15)),
                ('fitemname', models.CharField(max_length=255)),
                ('fmusician', models.CharField(max_length=100)),
                ('fcreatetime', models.DateTimeField()),
                ('factivity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sys_Para',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fparatype', models.CharField(max_length=255)),
                ('fparaname', models.CharField(max_length=255)),
                ('fparaorder', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fusername', models.CharField(max_length=255)),
                ('fuserid', models.IntegerField(primary_key=True)),
                ('fpassword', models.CharField(max_length=18)),
                ('fcreatetime', models.DateTimeField()),
                ('fstatus', models.CharField(max_length=255)),
                ('fdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fuserid', models.CharField(max_length=15)),
                ('fitemname', models.CharField(max_length=255)),
                ('factivity', models.CharField(max_length=20)),
                ('factivitytime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fusername', models.CharField(max_length=255)),
                ('fsex', models.CharField(max_length=4)),
                ('fuserid', models.CharField(max_length=15)),
            ],
        ),
    ]
